package rules

// Default is the built-in rule set.
var Default = map[string]*Rule{
	// ── Non-mutable ──────────────────────────────────────────
	"ls":       {Default: true},
	"cat":      {Default: true},
	"head":     {Default: true},
	"tail":     {Default: true},
	"less":     {Default: true},
	"bat":      {Default: true},
	"file":     {Default: true},
	"stat":     {Default: true},
	"wc":       {Default: true},
	"grep":     {Default: true},
	"rg":       {Default: true},
	"ag":       {Default: true},
	"sort":     {Default: true},
	"uniq":     {Default: true},
	"cut":      {Default: true},
	"tr":       {Default: true},
	"diff":     {Default: true},
	"comm":     {Default: true},
	"tac":      {Default: true},
	"rev":      {Default: true},
	"paste":    {Default: true},
	"column":   {Default: true},
	"expand":   {Default: true},
	"tree":     {Default: true},
	"pwd":      {Default: true},
	"whoami":   {Default: true},
	"hostname": {Default: true},
	"uname":    {Default: true},
	"date":     {Default: true},
	"printenv": {Default: true},
	"which":    {Default: true},
	"echo":     {Default: true},
	"printf":   {Default: true},
	"test":     {Default: true},
	"true":     {Default: true},
	"false":    {Default: true},
	"basename": {Default: true},
	"dirname":  {Default: true},
	"realpath": {Default: true},
	"readlink": {Default: true},
	"ps":       {Default: true},
	"df":       {Default: true},
	"du":       {Default: true},
	"free":     {Default: true},
	"ss":       {Default: true},
	"dig":      {Default: true},
	"ping":     {Default: true},
	"seq":      {Default: true},
	"sleep":    {Default: true},
	"bc":       {Default: true},
	"expr":     {Default: true},

	// Data processing
	"jq":        {Default: true},
	"base64":    {Default: true},
	"md5sum":    {Default: true},
	"sha1sum":   {Default: true},
	"sha256sum": {Default: true},
	"sha512sum": {Default: true},
	"b3sum":     {Default: true},
	"hexdump":   {Default: true},
	"xxd":       {Default: true},
	"od":        {Default: true},

	// Flag-dependent
	"yq": {
		Default:   true,
		DenyFlags: []string{"-i", "--in-place"},
	},
	"sed": {
		Default:   true,
		DenyFlags: []string{"-i", "--in-place"},
	},
	"find": {
		Default:   true,
		DenyFlags: []string{"-exec", "-execdir", "-ok", "-okdir", "-delete", "-fprint", "-fls"},
	},

	// ── Mutable ─────────────────────────────────────────────
	"rm":      {Default: false},
	"rmdir":   {Default: false},
	"mv":      {Default: false},
	"cp":      {Default: false},
	"mkdir":   {Default: false},
	"touch":   {Default: false},
	"chmod":   {Default: false},
	"chown":   {Default: false},
	"chgrp":   {Default: false},
	"ln":      {Default: false},
	"tee":     {Default: false},
	"install": {Default: false},
	"sudo":    {Default: false},
	"doas":    {Default: false},
	"su":      {Default: false},
	"kill":    {Default: false},
	"pkill":   {Default: false},
	"curl":    {Default: false},
	"wget":    {Default: false},
	"ssh":     {Default: false},
	"scp":     {Default: false},
	"rsync":   {Default: false},
	"nc":      {Default: false},
	"make":    {Default: false},
	"xargs":   {Default: false},
	"awk":     {Default: false},
	"perl":    {Default: false},
	"python":  {Default: false},
	"python3": {Default: false},
	"ruby":    {Default: false},
	"node":    {Default: false},
	"bash":    {Default: false},
	"sh":      {Default: false},
	"eval":    {Default: false},
	"exec":    {Default: false},
	"source":  {Default: false},
	"apt":     {Default: false},
	"brew":    {Default: false},
	"npm":     {Default: false},
	"pip":     {Default: false},
	"pushd":   {Default: false},
	"popd":    {Default: false},
	"env":     {Default: false},

	// ── Nested subcommands ──────────────────────────────────
	"git": {
		Default:   false,
		DenyFlags: []string{"-C", "--work-tree", "--git-dir"},
		Subcommands: map[string]*Rule{
			"status":        {Default: true},
			"diff":          {Default: true},
			"log":           {Default: true},
			"show":          {Default: true},
			"blame":         {Default: true},
			"shortlog":      {Default: true},
			"reflog":        {Default: true},
			"whatchanged":   {Default: true},
			"ls-files":      {Default: true},
			"ls-tree":       {Default: true},
			"ls-remote":     {Default: true},
			"describe":      {Default: true},
			"rev-parse":     {Default: true},
			"name-rev":      {Default: true},
			"merge-base":    {Default: true},
			"cherry":        {Default: true},
			"count-objects": {Default: true},
			"fsck":          {Default: true},
			"check-ignore":  {Default: true},
			"help":          {Default: true},
			"version":       {Default: true},
			"range-diff":    {Default: true},
			"var":           {Default: true},
			"commit":        {Default: false},
			"push":          {Default: false},
			"pull":          {Default: false},
			"merge":         {Default: false},
			"rebase":        {Default: false},
			"reset":         {Default: false},
			"checkout":      {Default: false},
			"switch":        {Default: false},
			"clone":         {Default: false},
			"init":          {Default: false},
			"add":           {Default: false},
			"clean":         {Default: false},
			"apply":         {Default: false},
			"am":            {Default: false},
			"bisect":        {Default: false},
			"cherry-pick":   {Default: false},
			"fetch":         {Default: false},
			"mv":            {Default: false},
			"rm":            {Default: false},
			"restore":       {Default: false},
			"revert":        {Default: false},
			"remote": {
				Default: false,
				Subcommands: map[string]*Rule{
					"-v":        {Default: true},
					"--verbose": {Default: true},
					"show":      {Default: true},
					"list":      {Default: true},
					"get-url":   {Default: true},
					"add":       {Default: false},
					"remove":    {Default: false},
					"rm":        {Default: false},
					"rename":    {Default: false},
					"set-url":   {Default: false},
					"set-head":  {Default: false},
					"prune":     {Default: false},
				},
			},
			"branch": {
				Default:   false,
				DenyFlags: []string{"-d", "-D", "--delete", "-m", "-M", "--move"},
				Subcommands: map[string]*Rule{
					"-l":             {Default: true},
					"--list":         {Default: true},
					"-a":             {Default: true},
					"-r":             {Default: true},
					"-v":             {Default: true},
					"--verbose":      {Default: true},
					"--show-current": {Default: true},
					"--contains":     {Default: true},
					"--no-contains":  {Default: true},
					"--merged":       {Default: true},
					"--no-merged":    {Default: true},
				},
			},
			"tag": {
				Default:   false,
				DenyFlags: []string{"-d", "--delete"},
				Subcommands: map[string]*Rule{
					"-l":       {Default: true},
					"--list":   {Default: true},
					"-n":       {Default: true},
					"-v":       {Default: true},
					"--verify": {Default: true},
				},
			},
			"stash": {
				Default: false,
				Subcommands: map[string]*Rule{
					"list":   {Default: true},
					"show":   {Default: true},
					"push":   {Default: false},
					"pop":    {Default: false},
					"apply":  {Default: false},
					"drop":   {Default: false},
					"clear":  {Default: false},
					"branch": {Default: false},
					"create": {Default: false},
				},
			},
			"submodule": {
				Default: false,
				Subcommands: map[string]*Rule{
					"status":        {Default: true},
					"summary":       {Default: true},
					"add":           {Default: false},
					"init":          {Default: false},
					"deinit":        {Default: false},
					"update":        {Default: false},
					"sync":          {Default: false},
					"foreach":       {Default: false},
					"absorbgitdirs": {Default: false},
				},
			},
			"worktree": {
				Default: false,
				Subcommands: map[string]*Rule{
					"list":   {Default: true},
					"add":    {Default: false},
					"remove": {Default: false},
					"prune":  {Default: false},
					"repair": {Default: false},
					"move":   {Default: false},
					"lock":   {Default: false},
					"unlock": {Default: false},
				},
			},
			"config": {
				Default:   true,
				DenyFlags: []string{"--global", "--system", "--file"},
			},
		},
	},

	"go": {
		Default: false,
		Subcommands: map[string]*Rule{
			"version": {Default: true},
			"env":     {Default: true},
			"list":    {Default: true},
			"doc":     {Default: true},
			"vet":     {Default: true},
			"test": {
				Default:   true,
				DenyFlags: []string{"-c", "--coverprofile"},
			},
			"build":    {Default: false},
			"run":      {Default: false},
			"install":  {Default: false},
			"get":      {Default: false},
			"generate": {Default: false},
			"mod": {
				Default: false,
				Subcommands: map[string]*Rule{
					"download": {Default: true},
					"verify":   {Default: true},
					"graph":    {Default: true},
					"why":      {Default: true},
					"tidy":     {Default: false},
					"edit":     {Default: false},
					"init":     {Default: false},
					"vendor":   {Default: false},
				},
			},
			"tool": {
				Default: false,
				Subcommands: map[string]*Rule{
					"vet":   {Default: true},
					"cover": {Default: true},
					"pprof": {Default: true},
					"trace": {Default: true},
					"dist":  {Default: false},
				},
			},
		},
	},

	"cargo": {
		Default: false,
		Subcommands: map[string]*Rule{
			"version":        {Default: true},
			"--version":      {Default: true},
			"-V":             {Default: true},
			"check":          {Default: true},
			"test":           {Default: true},
			"doc":            {Default: true},
			"tree":           {Default: true},
			"locate-project": {Default: true},
			"metadata":       {Default: true},
			"search":         {Default: true},
			"info":           {Default: true},
			"build":          {Default: false},
			"run":            {Default: false},
			"install":        {Default: false},
			"add":            {Default: false},
			"remove":         {Default: false},
			"rm":             {Default: false},
			"publish":        {Default: false},
			"init":           {Default: false},
			"new":            {Default: false},
			"clean":          {Default: false},
			"update":         {Default: false},
			"fetch":          {Default: false},
			"generate":       {Default: false},
			"login":          {Default: false},
			"logout":         {Default: false},
			"owner":          {Default: false},
			"yank":           {Default: false},
		},
	},

	"gh": {
		Default: false,
		Subcommands: map[string]*Rule{
			"version": {Default: true},
			"api":     {Default: true},
			"pr": {
				Default: false,
				Subcommands: map[string]*Rule{
					"list":   {Default: true},
					"view":   {Default: true},
					"status": {Default: true},
					"checks": {Default: true},
					"diff":   {Default: true},
					"create": {Default: false},
					"edit":   {Default: false},
					"merge":  {Default: false},
					"close":  {Default: false},
					"reopen": {Default: false},
					"ready":  {Default: false},
					"review": {Default: false},
				},
			},
			"issue": {
				Default: false,
				Subcommands: map[string]*Rule{
					"list":     {Default: true},
					"view":     {Default: true},
					"status":   {Default: true},
					"search":   {Default: true},
					"create":   {Default: false},
					"edit":     {Default: false},
					"close":    {Default: false},
					"reopen":   {Default: false},
					"delete":   {Default: false},
					"transfer": {Default: false},
					"pin":      {Default: false},
					"unpin":    {Default: false},
					"develop":  {Default: false},
				},
			},
			"repo": {
				Default: false,
				Subcommands: map[string]*Rule{
					"list":      {Default: true},
					"view":      {Default: true},
					"clone":     {Default: true},
					"fork":      {Default: true},
					"search":    {Default: true},
					"create":    {Default: false},
					"delete":    {Default: false},
					"edit":      {Default: false},
					"rename":    {Default: false},
					"sync":      {Default: false},
					"archive":   {Default: false},
					"unarchive": {Default: false},
					"transfer":  {Default: false},
				},
			},
			"release": {
				Default: false,
				Subcommands: map[string]*Rule{
					"list":     {Default: true},
					"view":     {Default: true},
					"download": {Default: true},
					"create":   {Default: false},
					"edit":     {Default: false},
					"delete":   {Default: false},
					"upload":   {Default: false},
				},
			},
			"workflow": {
				Default: false,
				Subcommands: map[string]*Rule{
					"list":    {Default: true},
					"view":    {Default: true},
					"run":     {Default: false},
					"rerun":   {Default: false},
					"cancel":  {Default: false},
					"disable": {Default: false},
					"enable":  {Default: false},
				},
			},
			"run": {
				Default: false,
				Subcommands: map[string]*Rule{
					"list":     {Default: true},
					"view":     {Default: true},
					"watch":    {Default: true},
					"download": {Default: true},
					"rerun":    {Default: false},
					"cancel":   {Default: false},
					"delete":   {Default: false},
				},
			},
			"auth": {
				Default: false,
				Subcommands: map[string]*Rule{
					"status":    {Default: true},
					"login":     {Default: false},
					"logout":    {Default: false},
					"token":     {Default: false},
					"setup-git": {Default: false},
					"refresh":   {Default: false},
				},
			},
			"gpg-key": {
				Default: false,
				Subcommands: map[string]*Rule{
					"list":   {Default: true},
					"add":    {Default: false},
					"delete": {Default: false},
				},
			},
			"ssh-key": {
				Default: false,
				Subcommands: map[string]*Rule{
					"list":   {Default: true},
					"add":    {Default: false},
					"delete": {Default: false},
				},
			},
		},
	},

	"kubectl": {
		Default: false,
		Subcommands: map[string]*Rule{
			"get":           {Default: true},
			"describe":      {Default: true},
			"logs":          {Default: true},
			"top":           {Default: true},
			"api-resources": {Default: true},
			"api-versions":  {Default: true},
			"version":       {Default: true},
			"cluster-info":  {Default: true},
			"auth": {
				Default: false,
				Subcommands: map[string]*Rule{
					"can-i":     {Default: true},
					"reconcile": {Default: true},
					"whoami":    {Default: true},
				},
			},
			"apply":        {Default: false},
			"create":       {Default: false},
			"delete":       {Default: false},
			"edit":         {Default: false},
			"patch":        {Default: false},
			"replace":      {Default: false},
			"rollout":      {Default: false},
			"scale":        {Default: false},
			"exec":         {Default: false},
			"cp":           {Default: false},
			"port-forward": {Default: false},
			"proxy":        {Default: false},
			"attach":       {Default: false},
			"config":       {Default: false},
		},
	},

	"docker": {
		Default: false,
		Subcommands: map[string]*Rule{
			"version": {Default: true},
			"info":    {Default: true},
			"images":  {Default: true},
			"ps":      {Default: true},
			"inspect": {Default: true},
			"logs":    {Default: true},
			"stats":   {Default: true},
			"top":     {Default: true},
			"port":    {Default: true},
			"history": {Default: true},
			"search":  {Default: true},
			"volume": {
				Default: false,
				Subcommands: map[string]*Rule{
					"ls":      {Default: true},
					"inspect": {Default: true},
					"create":  {Default: false},
					"rm":      {Default: false},
					"prune":   {Default: false},
				},
			},
			"network": {
				Default: false,
				Subcommands: map[string]*Rule{
					"ls":         {Default: true},
					"inspect":    {Default: true},
					"create":     {Default: false},
					"rm":         {Default: false},
					"prune":      {Default: false},
					"connect":    {Default: false},
					"disconnect": {Default: false},
				},
			},
			"build":   {Default: false},
			"run":     {Default: false},
			"pull":    {Default: false},
			"push":    {Default: false},
			"rm":      {Default: false},
			"rmi":     {Default: false},
			"stop":    {Default: false},
			"start":   {Default: false},
			"restart": {Default: false},
			"kill":    {Default: false},
			"exec":    {Default: false},
			"cp":      {Default: false},
			"create":  {Default: false},
			"compose": {Default: false},
			"login":   {Default: false},
			"logout":  {Default: false},
			"tag":     {Default: false},
			"commit":  {Default: false},
			"save":    {Default: false},
			"load":    {Default: false},
			"system":  {Default: false},
			"swarm":   {Default: false},
			"service": {Default: false},
		},
	},
}
